# Generated by Django 6.0.6 on 2026-06-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meeting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Owner/Admin'), ('TL', 'Team Leader'), ('EMPLOYEE', 'Employee'), ('INTERN', 'Intern')], default='EMPLOYEE', max_length=20),
        ),
    ]
