# Generated by Django 6.0.6 on 2026-06-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meeting_target_roles_participant_rsvp_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Link for online meetings', max_length=500, null=True),
        ),
    ]
