# Generated by Django 6.0.6 on 2026-06-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='action_items_raw',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='decisions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
