# Generated by Django 6.0.6 on 2026-06-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_meetingminutes_action_items_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='docx_export',
            field=models.FileField(blank=True, null=True, upload_to='exports/docx/'),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='pdf_export',
            field=models.FileField(blank=True, null=True, upload_to='exports/pdf/'),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Transcript'), ('PROCESSING', 'Processing Transcript'), ('GENERATING', 'Generating AI Summary'), ('READY', 'Minutes Ready'), ('NO_TRANSCRIPT', 'No Transcript Available')], default='PENDING', max_length=20),
        ),
    ]
