# Generated by Django 6.0.6 on 2026-06-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_meetingminutes_docx_export_meetingminutes_pdf_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='processing_logs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
