# Generated by Django 6.0.6 on 2026-06-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customuser_company_name_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='mom_audio/'),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='speaker_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Stores speaker diarization stats'),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='txt_export',
            field=models.FileField(blank=True, null=True, upload_to='exports/txt/'),
        ),
    ]
