# Generated by Django 6.0.6 on 2026-06-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_participant_external_email_participant_external_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='meeting_attachments/'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
