# Generated by Django 6.0.6 on 2026-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_meeting_attachment_alter_meeting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminutes',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Transcript'), ('PROCESSING', 'Processing Transcript'), ('GENERATING', 'Generating AI Summary'), ('READY', 'Minutes Ready'), ('NO_TRANSCRIPT', 'No Transcript Available'), ('FAILED', 'Transcription Failed')], default='PENDING', max_length=20),
        ),
    ]
